### ISSUE TITLE
JOSS review - documentation

### ISSUE THREAD

**Issue by PeerHerholz** [CyclotronResearchCentre/bidsme#5]
Ahoi hoi @nbeliy & co-authors,

this is in reference to the review I'm currently conducting for `JOSS` [here](https://github.com/openjournals/joss-reviews/issues/5575) .

First of all, thank you very much for your dedicated work on this tool and your respective submission to `JOSS`.
Based on the [review process and included checkboxes](https://github.com/openjournals/joss-reviews/issues/5575#issuecomment-1627300948), I would like to suggest a few things.

IMHO, it would be great if you could add a small documentation (e.g. via [ReadTheDocs](https://readthedocs.org/), as the current state of the repository and split between `github`/`gitlab` complicates navigation and finding information a bit. Additionally, this would allow to add `API` method documentation and integrating the examples.

I'm very sorry if I missed something obvious, misunderstood something or assumed something wrong. Please let me know if that is the case, as well as if you have any questions. Thanks again for creating this important software tool.

Cheers, Peer

**Comment by nbeliy** [comment]
I've updated the documentation in doc, but not sure if will ever have time to create stand-alone documentation with the API.

**Comment by PeerHerholz** [comment]
Hi @nbeliy,

thanks for the update. Just confirming with @emdupre if this works re the `JOSS` requirements?

**Comment by emdupre** [comment]
Hi @PeerHerholz and @nbeliy,

Thanks for starting this conversation ! To confirm, the JOSS review criteria for API documentation are [linked here](https://joss.readthedocs.io/en/latest/review_criteria.html#api-documentation) and note:

> Reviewers should check that the software API is documented to a suitable level.  
>     **Good:** All functions/methods are documented including example inputs and outputs
>     **OK:** Core API functionality is documented
>     **Bad (not acceptable):** API is undocumented


To confirm, then : we require---at a minimum---that all of the core API functionality is documented. It seems that the API documentation has been manually generated to date in the `doc` folder. This makes it somewhat difficult to confirm if all core functionality is covered, which is likely where the confusion arose.

@PeerHerholz and @TheChymera, when you re-review the docs, would you be able to read through with this consideration in mind ? 

Otherwise @nbeliy, as @PeerHerholz suggested, you could use Sphinx to auto-generate all of your API documentation, such that it would automatically reach **Good** status per JOSS's definitions. This is not required for the JOSS review process, though !

**Comment by ChristophePhillips** [comment]
Hi @emdupre and @PeerHerholz,

Thank you for your constructive feedback!

FYI @nbeliy is currently enjoying a well deserved holiday break, so we'll come back to you in a couple of weeks only. 😃

**Comment by nbeliy** [comment]
Hi @emdupre and @PeerHerholz,
I will try to add documentation on readthesedocs, but it may take some time. I used human-readable python docstrings, and importing them using doxigen or sphynx will require rewriting all docstrings.

I tried to use pydoc, and it worked quite nice, but not sure if it's compatible with readthesedocs.

**Comment by nbeliy** [comment]
Closed as published
